services:

  mariadb:

    container_name: mariadb-${USERNAME}
    image: mariadb
    build: ./requirements/mariadb

    volumes:
      - mariadb:/var/lib/mysql

    env_file:
      - .env

    secrets:
      - db_root_passwd
      - db_passwd

    networks:
      - inception

    restart: always

    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -u root -p$$DB_ROOT_PASSWD --silent || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "pgrep mysqld > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  wordpress:

    container_name: wordpress-${USERNAME}
    image: wordpress
    build: ./requirements/wordpress

    depends_on:
      mariadb:
        condition: service_healthy 

    volumes:
      - wordpress:/var/www/wordpress

    env_file:
      - .env

    networks:
      - inception

    secrets:
      - wp_admin_passwd
      - wp_user_passwd
      - db_passwd  

    restart: always
    
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  nginx:
    container_name: nginx-${USERNAME} 
    image: nginx
    build: ./requirements/nginx

    depends_on:
      wordpress:
        condition: service_healthy

    volumes:
      - wordpress:/var/www/wordpress

    ports:
     - "443:443"

    env_file:
      - .env

    networks:
      - inception

    restart: always


secrets:
  db_root_passwd:
    file: ../secrets/db_root_passwd.txt
  db_passwd:
    file: ../secrets/db_passwd.txt
  wp_admin_passwd:
    file: ../secrets/wp_admin_passwd.txt
  wp_user_passwd:
    file: ../secrets/wp_user_passwd.txt

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tlebon/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tlebon/data/wordpress
      o: bind
      type: none
# ATTENTION au point de montage check sujet

networks:
  inception:
    name: inception