services:

  mariadb:

    container_name: mariadb
    image: mariadb:${USERNAME}
    build: ./requirements/mariadb

    volumes:
      - mariadb:/var/lib/mysql

    env_file:
      - .env

    networks:
      - inception

    restart: always

  wordpress:

    container_name: wordpress 
    image: wordpress:${USERNAME}
    build: ./requirements/wordpress

    depends_on:
      - mariadb

    volumes:
      - wordpress:/var/www/wordpress

    env_file:
      - .env

    networks:
      - inception
    
    restart: always

  nginx:
    container_name: nginx 
    image: nginx:${USERNAME}
    build: ./requirements/nginx

    depends_on:
    - wordpress

    expose:
     - "443"

    restart: always

 

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tlebon/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tlebon/data/wordpress
      o: bind
      type: none
# ATTENTION au point de montage check sujet

networks:
  inception:
    name: inception