services:

  mariadb:

    container_name: mariadb-${USERNAME}
    image: mariadb
    build: ./requirements/mariadb

    volumes:
      - mariadb:/var/lib/mysql

    env_file:
      - .env

    networks:
      - inception

    restart: always

    healthcheck:
      # test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${DB_ROOT_PASSWD}"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s # A fchecker

  wordpress:

    container_name: wordpress-${USERNAME}
    image: wordpress
    build: ./requirements/wordpress

    depends_on:
      mariadb:
        condition: service_healthy 

    volumes:
      - wordpress:/var/www/wordpress

    env_file:
      - .env

    networks:
      - inception
    
    restart: always

  nginx:
    container_name: nginx-${USERNAME} 
    image: nginx
    build: ./requirements/nginx

    depends_on:
    - wordpress

    volumes:
      - wordpress:/var/www/wordpress

    ports:
     - "443:443"

    env_file:
      - .env

    networks:
      - inception

    restart: always

 

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tlebon/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tlebon/data/wordpress
      o: bind
      type: none
# ATTENTION au point de montage check sujet

networks:
  inception:
    name: inception