services:

  mariadb:

    container_name: mariadb-${USERNAME}
    image: mariadb
    build: ./requirements/mariadb

    volumes:
      - mariadb:/var/lib/mysql

    env_file:
      - .env

    networks:
      - inception

    restart: always

    healthcheck:
      # test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s # A fchecker

  wordpress:

    container_name: wordpress-${USERNAME}
    image: wordpress
    build: ./requirements/wordpress

    depends_on:
      mariadb:
        condition: service_healthy 

    volumes:
      - wordpress:/var/www/wordpress

    env_file:
      - .env

    networks:
      - inception
    
    restart: always
    
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s


  nginx:
    container_name: nginx-${USERNAME} 
    image: nginx
    build: ./requirements/nginx

    depends_on:
      wordpress:
        condition: service_healthy

    volumes:
      - wordpress:/var/www/wordpress

    ports:
     - "443:443"

    env_file:
      - .env

    networks:
      - inception

    restart: always

    # healthcheck:
    #   test: ["CMD", "curl", "-f", "https://localhost"]  # Adjust for TLS
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3

 

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tlebon/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tlebon/data/wordpress
      o: bind
      type: none
# ATTENTION au point de montage check sujet

networks:
  inception:
    name: inception