version: "3.8"
#Find correct version

services:

  mariadb:

    container_name: mariadb
    image: mariadb:user
    build: ./requirements/mariadb

    volumes:
      - mariadb:/var/lib/mysql

    env_file:
      - .env

    networks:
      - inception

    restart: always

  wordpress:

    container_name: wordpress 
    image: wordpress:user
    build: ./requirements/wordpress

    depends_on:
      - mariadb

    volumes:
      - wordpress:/var/www/wordpress

    env_file:
      - .env

    networks:
      - inception
    
    restart: always

  # nginx:
  #   container_name: nginx 
  #   image: nginx:user
  #   build: ./requirements/nginx

  #   depends_on:
  #   - wordpress

  #   expose:
  #    - "9000"

  #   restart: always

 

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tlebon/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tlebon/data/wordpress
      o: bind
      type: none
# ATTENTION au point de montage check sujet

networks:
  inception:
    name: inception